### ISSUE TITLE
Empty values passed for relationship field result in SQLSTATE[23000]: Integrity constraint violation

### ISSUE THREAD

**Issue by timkelty** [craftcms/guest-entries#14]
[I posted this to SE](http://craftcms.stackexchange.com/a/17231/314) as there was already an issue, but I'm posting here as well, as it seems like it could be a bug, in either Guest Entries or Craft itself.

When an entries field (or presumably any relation field) is submitted as an array with an empty string, this error is thrown.

This would be common if you had a `<select>` with a "Choose One…" label and no value.

The same behavior can be triggered by passing a `null` or `['']` value to an entries field via `setContentFromPost`:

``` php
$entry->setContentFromPost([
  'product' => null
]);
```

or 

``` php
$entry->setContentFromPost([
  'product' => ['']
]);
```

So, to work around this, in `guestEntries.beforeSave`, I'm making sure it isn't `null` or `[0 => '']`:

``` php
$entry = $event->params['entry'];

// Seemingly, when the `fields.product` post data has an array
// with an empty string (like it does from an unselected <select>),
// we get a CDbException SQLSTATE[23000]: Integrity constraint violation error.
// The same thing seems to happen when setContentFromPost receives null on a
// relation field, so we'll coalesce to empty string.
$product = array_filter(craft()->request->getPost('fields.product'));
$entry->setContentFromPost([
  'product' => $product ?? '',
]);
```

**Comment by brandonkelly** [comment]
This isn’t an issue in Craft 3, so going to close it.
