### ISSUE TITLE
Email notifications

### ISSUE THREAD

**Issue by brandonkelly** [craftcms/guest-entries#21]

**Comment by billythekid** [comment]
FWIW I did write a plugin to do this based on the Craft2 version of the plugin: https://github.com/fortytwostudio/Email-On-Guest-Entry

**Comment by elvdm** [comment]
Alternatively, this functionality is also provided in https://github.com/therefinerynz/courier

It can listen to any event, including the events fired by the Guest Entries plugin, and send custom emails.

**Comment by davorpeic** [comment]
Any updates on this, what would be best way to send notification in Craft 3? Courier is not published in packagist and it looks it doesn't work

**Comment by brandonkelly** [comment]
We’re planning on adding a notification system to Craft at some point, so going to hold off on this until that’s a thing. In the meantime, the Notifications plugin looks like a solid solution.
