### ISSUE TITLE
Default author assignment setting doesn't work with large user sets

### ISSUE THREAD

**Issue by timkelty** [craftcms/guest-entries#25]
I have a guest entries section where thousands of existing users have author privileges, so they all show up in the dropdown…but only the first 100 of them, so I can never select the default user I want.

Thinking this selection should probably be an `elementselect` modal instead.

**Comment by brandonkelly** [comment]
Hey Tim, can you send a DB backup to support@craftcms.com, and point out which user you can't access? Not seeing anything in the code that would limit the dropdown to 100 users.

**Comment by brandonkelly** [comment]
Sorry didn’t realize this was for v1. Can fix it there. Will be harder to fix for v2 since the settings have been redesigned as an Editable Table, which currently doesn't support element select columns (cc craftcms/cms#811).

**Comment by timkelty** [comment]
Thanks. Will brainstorm on how to address this for v2 once this project is on Craft 3.

**Comment by brandonkelly** [comment]
Decided to just keep it a normal dropdown for v1, since in v1 the dropdown actually doubles as the way to enable/disable allowing guest entry submission for the section. So swapping it with a element select field would add confusion, unless we redesigned the settings to be more like they are in v2.

**Comment by timkelty** [comment]
> Will brainstorm on how to address this for v2 once this project is on Craft 3.

@brandonkelly can you reopen this? It is still an issue for Craft 3. The only way I can adjust settings is via project-config, as I have too many users for the settings templates to render.
