### ISSUE TITLE
Latest 1.5.2 Release doesn't return entry URL in AJAX Submissions

### ISSUE THREAD

**Issue by chasegiunta** [craftcms/guest-entries#27]
Though it's been committed to the v1 branch, and it's mentioned in the readme (I know, the readme on GitHub isn't the readme for the release):
>url (string) - live URL of the entry saved if it has a URL

The latest release doesn't return URLs.
https://github.com/craftcms/guest-entries/blob/0b638a5f145a419d41a0d265835172a43a6703b2/guestentries/controllers/GuestEntriesController.php#L118

Looks like @brandonkelly was close to releasing 1.5.3 with this new bit, but it never made it.

Anyway, downloading the latest on branch works

**Comment by takobell** [comment]
Tagged a 1.5.3 release, so should work now.
