### ISSUE TITLE
Redirect not working on Craft 3 RC4

### ISSUE THREAD

**Issue by cavellblood** [craftcms/guest-entries#29]
I've copied the code that is in the readme file and the `redirect` hidden input is not working. It just goes to the home page or root directory of the site. The entries are saving correctly. The only thing that isn't working is the `redirect`.

My code is something like this:

```
<form method="post" action="" accept-charset="UTF-8">
    {{ csrfInput() }}
    <input type="hidden" name="action" value="guest-entries/save">
    <input type="hidden" name="redirect" value="transactions">
    <input type="hidden" name="sectionId" value="3">

    <label for="memo">Memo</label>
    <input type="text" name="fields[memo]" />

    <label for="amount">Amount</label>
    <input type="number" name="fields[amount]" step="0.01" />

    <input type="submit" value="Save">
</form>
```

I even tried removing the empty `action=""` from the `form` tag or setting it to where I wanted it to redirect. Still doesn't work. I'm guessing it might be because I'm using Craft 3 RC4 and this might be fixed in the future.

Any suggestions?

**Comment by cavellblood** [comment]
I've also just tried `action="/transactions"` and that didn't seem to change anything.

**Comment by cavellblood** [comment]
Here's my settings for the guest entries plugin.

<img width="698" alt="screen shot 2018-01-04 at 8 44 20 pm" src="https://user-images.githubusercontent.com/727740/34593386-214952be-f190-11e7-9714-dd8dcef0aaed.png">

I've tried toggling the **_Validate?_** setting and the **_Enable CSRF Protection?_** settings but that doesn't change anything either. Not that it should, I'm just trying anything to see if it would affect it.

**Comment by angrybrad** [comment]
The value of the redirect needs to be hashed like so: https://github.com/craftcms/docs/blob/master/en/changes-in-craft-3.md#redirect-params

I've updated the Guest Entries README.md with the correct example, too: https://github.com/craftcms/guest-entries#usage

**Comment by cavellblood** [comment]
Thanks for pointing me in the right direction, @angrybrad.
