### ISSUE TITLE
changes to syntax after C3 RC15

### ISSUE THREAD

**Issue by thisisjamessmith** [craftcms/guest-entries#31]
Worth noting that after upgrading to RC15 the syntax changed in how to reference errors - it should now be something like this, prefixing the field handle with "field:"

`submission.getErrors('field:' ~ field.handle)`

**Comment by thisisjamessmith** [comment]
GAH, upgrading to RC16 seems to have changed it back to how it was. The joys of pre-release.

**Comment by angrybrad** [comment]
Just wait until RC17 and we break it again. ;)

Glad you're all sorted.
