### ISSUE TITLE
Error after 99 entries

### ISSUE THREAD

**Issue by fa6ian** [craftcms/guest-entries#35]
I'm receiving 500 (Internal Server Errors) after 99 entries. Is there any way to bypass this limit?

**Comment by brandonkelly** [comment]
Where are you getting the error?

**Comment by fa6ian** [comment]
Hi Brandon,

I think I figured it out. Looking at the stack trace, the specific error is: Craft\Exception: Could not find a unique URI for this element.

So I'm using guest entries to have guests submit votes of their favorite tea blend. Say I have 5 tea blends, and one of those blends is titled "Hazelnut Truffle". Craft takes care of assigning a unique slug to that submission until it reaches hazelnut-truffle-99. My guess is that it's resetting to an existing uri (perhaps hazelnut-truffle-1) hence the error.

Any suggestions on how to get past this?

Thanks,

Fabian

**Comment by fa6ian** [comment]
Ok, figured it out. I see you added a maxSlugIncrement config setting. Thanks.

**Comment by angrybrad** [comment]
Yup! Glad you're all sorted.
