### ISSUE TITLE
Required element fields do not pass validation when they should

### ISSUE THREAD

**Issue by timkelty** [craftcms/guest-entries#38]
In my form I have fields like:

```
      <input type="hidden" name="fields[materials][]" value="5416">
```

- `materials` is a entries field, marked required in the entry type.
- I have "Validate?" enabled for this section
- On submission I get the error "Materials cannot be blank."
- If I un-require the field, the submission works, and the materials field data is populated from the submission as it should be.
- Required validation on other fields (text) seems to work as expected.
- I thought maybe it had to do with the default author not having appropriate permissions, so I tried them as admin and it still didn't work

Craft CMS 3.0.12, Guest Entries 2.1.3

**Comment by timkelty** [comment]
It might be an issue with validating against the wrong submitted `typeId`, as I have a required entries field that _is_ working, but it is common across both this section's entry types, while the one that isn't working is unique to the entry type.

**Comment by brandonkelly** [comment]
I’m not able to reproduce this. Can you send a database backup, your `composer.json` & `composer.lock` files, and relavant template code over to support@craftcms.com ?
