### ISSUE TITLE
Default author assignment only showing "Admin"

### ISSUE THREAD

**Issue by christopherdowson** [craftcms/guest-entries#44]
I've set up a user with permissions to create and edit entries in the section I want guest entries to post to, but all I can select from the dropdown is Admin. 

Is there a setting I've missed?

**Comment by angrybrad** [comment]
Just tested this on the latest release with a user that has create/edit permissions for a section and they showed up in the default author dropdown list, so going to go with [Brandon's theory](https://github.com/craftcms/guest-entries/issues/44#issuecomment-460915331).

**Comment by christopherdowson** [comment]
@brandonkelly Yes, the user is activated BUT it seems their group assignment didn't save. I've assigned them and it's all working well now. At least it wasn't something major. 

Thanks.
