### ISSUE TITLE
Settings Not Saving

### ISSUE THREAD

**Issue by tokersey** [craftcms/guest-entries#45]
Hello,

When going to the settings of Guest Entries and saving new settings, the changes are not being saved. The page redirects to the admin/settings page and says the plugin settings are saved. However, when returning to the Guest Entries settings, they are reverted back to the previous state. In order to work around the issue, I had to revert PHP to 7.1 and Guest entries to 2.2.1. Please let me know if you have any questions.

Craft 3.1.8
Guest Entries 2.2.2
PHP 7.2.8
MySQL 5.7.23

Thanks,

Todd Kersey

**Comment by brandonkelly** [comment]
Just released 2.2.2.1 with a fix for this.
