### ISSUE TITLE
Image Exception -- can't save assets from front-end entry form

### ISSUE THREAD

**Issue by daltonrooney** [craftcms/guest-entries#49]
I'm using Craft 3.2 RC1 with Guest Entries 2.2.3. I have a guest entry form set up and works just fine unless I try to upload an image. My abbreviated form looks like this:

```
<form method="post" action="" enctype="multipart/form-data" accept-charset="UTF-8">
    {{ csrfInput() }}

    <input type="hidden" name="action" value="guest-entries/save">
    <input type="hidden" name="sectionUid" value="25e26550-2b9f-418a-84cc-4e08ca46913a">

    <label for="title">Title</label>
    <input id="title" type="text" name="title"/>

    <label for="thumbnailImage">Thumbnail Image</label>
    <input type="file" id="thumbnailImage" name="fields[thumbnailImage]" value="Upload">

    <input type="submit" value="Submit">
</form>
```

When I try to upload an image, I get an Image Exception error:

```
Image Exception – craft\errors\ImageException
The file “assets5d239a84ae0f09.86917575.jpg” does not appear to be an image.
```

Ae file with that name is written to the temp directory, but is empty (zero bytes).

The odd thing is that the correct and working image file is also copied to the asset directory, but not visible from the Assets panel in Craft.

Any thoughts?

**Comment by PaulvanKaam** [comment]
Updating Craft and Plugin fixed the problem for me 

`Fetching available updates ... done
Performing 3 updates:

    - craft 3.2.0 => 3.2.1
    - guest-entries 2.2.3 => 2.2.4
`
