### ISSUE TITLE
Allow customised authorUsername in the form

### ISSUE THREAD

**Issue by max8hine** [craftcms/guest-entries#52]
### Current behaviour:
I believe the plugin cant does not change `authorUsername` in the front-end.

e.g

```html
<input type="hidden" name="authorUsername" :value="user@example.com" />
```

and `authorUsername` is defined in plugin in settings.

### Desire behaviour:

the `guest-entries/save` action can take below value

```html
<input type="hidden" name="authorId" :value="userId" />
```

**Comment by brandonkelly** [comment]
Guest Entries doesn’t support passing a custom `authorUsername` value – that’s just something it includes in the response info when submitting over Ajax. That said, if you really want to add support for the form passing its own `authorUsername` param, you could make that happen by writing a module that hooks into the [beforeSaveEntry](https://github.com/craftcms/guest-entries#the-beforesaveentry-event) event.
