### ISSUE TITLE
How to set postDate in submission

### ISSUE THREAD

**Issue by uksitebuilder** [craftcms/guest-entries#58]
Hi,

I have guest entries being submitted but disabled by dfault (so they can be checked before being published)

However, the post Date appears to be blank.

How can I set the date in the form to the date is the date/time as of the submission?

**Comment by billymedia** [comment]
<input type="hidden" name="postDate" value="{{ now|date("Y-m-j H:i:s") }}" />

**Comment by AugustMiller** [comment]
Billy’s answer is correct!

We’ve added all the properties that can be sent with a submission to the readme, including `postDate` and `expiryDate`.
